name: check_cids

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test-cids:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install uv dependencies
      run: uv sync

    - name: install IPFS
      run: |
        wget -q https://dist.ipfs.tech/kubo/${IPFS_VERSION}/kubo_${IPFS_VERSION}_linux-amd64.tar.gz
        tar -xvzf kubo_${IPFS_VERSION}_linux-amd64.tar.gz
        pushd kubo
        sudo bash install.sh
        popd
        ipfs --version
      env:
        IPFS_VERSION: v0.32.1
    - name: init IPFS
      run: |
        ipfs init --profile server,announce-off
    - name: configure known IPFS peers
      run: |
        uv run wget -q https://raw.githubusercontent.com/orcestra-campaign/ipfs_tools/refs/heads/main/scripts/add_peers.py -O - | uv run python - -f https://raw.githubusercontent.com/orcestra-campaign/ipfs_tools/refs/heads/main/known_peers.yaml
    - name: run IPFS in background
      run: |
        ipfs daemon 2>ipfs.log | grep -i -o -m1 'Daemon is ready' & tail -F --pid=$! ipfs.log
    - name: Run CID validation tests
      run: |
        uv run pytest tests/test_cids.py